packages:
  - "errors"
  - "db"
  - "model"
  - "api"
  - "tma-init-data"
  - "tma-react"
  - "telegram-bot"
  - "ip"
  - "client"
  - "object"
  - "json"
  - "sleep"
  - "retry"
  - "hooks"
  - "types"